[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmd = "npm install"

[phases.build]
cmd = "echo 'Build complete'"

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production" 